import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/providers/auth-provider'
import Header from '@/components/shared/header'
import { Toaster } from '@/components/ui/toaster'
import { Provider } from 'react-redux'
import StoreProvider from '@/providers/store-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <StoreProvider>
            <Header />
            <div>{children}</div>
            <Toaster />
          </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
